print ("Welcome, please type your information.")
name=input("Enter full name: ")
dep=input("Enter your Department: ")
con=input("Enter your Contact email: ")
access=input("Enter your Access Level: ")
print ("|---------------------------------------------------------------------|")
print ("|                                             APEX ENTERTAINMENT PASS |")
print ("|---------------------------------------------------------------------|")
print ("| Attendee: "+name.ljust(58)+"|")
print ("| Org: BCH "+dep.ljust(59)+"|")
print ("| Contact: "+con.ljust(59)+"|")
print ("| Access: "+access.ljust(60)+"|")
print ("| Issuer: BCH Software Terminal System                                |")
print ("|---------------------------------------------------------------------|")
