print ("Welcome, please type your information")
name=input("Enter first name ")
name2=input("Enter last name ")
dep=input("Enter your Department ")
con=input("Enter your Contact email ")
access=input("Enter your Access Level ")
print ("---------------------------------------------------------------------")
print (name+name2)
print (dep)
print (con)
print (access)
print ("---------------------------------------------------------------------")
